### ISSUE TITLE
Examples Don't Compile (*Raspberry Pi*)

### ISSUE THREAD

**Issue by mannkind** [matheusbrat/RF24SH#2]
Matheus,

I'm really excited about trying out your project, but there seems to be an issue on the RPi. I cannot get any of your examples to compile -- RPi B Rev2.0, using Raspbian.

The initial error is about the type-specifier... which I fixed (I think), but after that the compiler errors are over my head.

I know the radio is working; it is receiving data from an Arduino Nano using another test program.

One more note: If I go all the way back to commit e09efb070b086966a1bf2ac83c62bc5f73f9c8d0 it'll compile, but it just runs and exits.

Any ideas?

(Awesome project by the way!)

**Comment by thomasqbrady** [comment]
I had the same issue. Matheus couldn't recreate the issue at the time. Would love to see this working.

**Comment by mannkind** [comment]
Hmm. Well I'm hoping he has an idea of what's going on... 

I do plan on taking a look this weekend … but C++ isn't a language I have much of experience with.

**Comment by chriserik** [comment]
I'm also having this issue. I'd be very thankful for a solution!

**Comment by matheusbrat** [comment]
That is so strange, maybe I should update my RPi OS to try to reproduce this. 

I don't have my RPi with me right now, but I will try to look into this. If you could, please paste here the GCC version, OS, and any other information that you guys think it could be useful.

**Comment by mannkind** [comment]
Personally, I'm running Raspbian and any updates that `rpi-update` might provide.

$ uname -a
Linux 3.6.11+ #557 PREEMPT Wed Oct 2 18:49:09 BST 2013 armv6l GNU/Linux

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Debian 4.6.3-14+rpi1)

**Comment by grantsmith1969** [comment]
Here are the compile errors:

root@raspberrypi:/home/grant/RF24SH/RF24SH/examples/rpi_station# make
cd ../../librf24/rpi; make all
make[1]: Entering directory `/home/grant/RF24SH/RF24SH/librf24/rpi'
g++ -shared -Wl,-soname,librf24.so.1 -Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s  -o librf24.so.1.0 compatibility.o gpio.o spi.o RF24.o
make[1]: Leaving directory`/home/grant/RF24SH/RF24SH/librf24/rpi'
g++ -L../../librf24/rpi/ -lrf24 ../../config.h ../../GenericStation.h ../../Station.h ../../PMessage.h ../../GenericStation.cpp ../../Station.cpp ../../PMessage.cpp rpi_station.cpp -o rpi_station
In file included from ../../GenericStation.h:78:0:
../../GenericStation-impl.h:14:2: warning: #warning Are you sure, you are calling the correct constructor? [-Wcpp]
../../GenericStation-impl.h: In constructor ‘GenericStation<MESSAGE_TYPE>::GenericStation(uint8_t, uint8_t)’:
../../GenericStation-impl.h:16:1: error: expected identifier before ‘{’ token
In file included from ../../GenericStation.h:78:0,
                 from ../../Station.h:11:
../../GenericStation-impl.h:14:2: warning: #warning Are you sure, you are calling the correct constructor? [-Wcpp]
../../GenericStation-impl.h: In constructor ‘GenericStation<MESSAGE_TYPE>::GenericStation(uint8_t, uint8_t)’:
../../GenericStation-impl.h:16:1: error: expected identifier before ‘{’ token
../../PMessage.cpp: In member function ‘void PMessage::print()’:
../../PMessage.cpp:46:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:48:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:50:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:52:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:54:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:56:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
../../PMessage.cpp:58:2: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
In file included from ../../GenericStation.h:78:0,
                 from ../../Station.h:11,
                 from rpi_station.cpp:2:
../../GenericStation-impl.h:14:2: warning: #warning Are you sure, you are calling the correct constructor? [-Wcpp]
../../GenericStation-impl.h: In constructor ‘GenericStation<MESSAGE_TYPE>::GenericStation(uint8_t, uint8_t)’:
../../GenericStation-impl.h:16:1: error: expected identifier before ‘{’ token
rpi_station.cpp: At global scope:
rpi_station.cpp:9:1: error: invalid use of template-name ‘Station’ without an argument list
rpi_station.cpp: In function ‘int main(int, char__)’:
rpi_station.cpp:19:2: error: ‘p’ was not declared in this scope
rpi_station.cpp:19:10: error: expected type-specifier before ‘Station’
rpi_station.cpp:19:10: error: expected ‘;’ before ‘Station’
rpi_station.cpp: In function ‘void loop()’:
rpi_station.cpp:26:9: error: ‘p’ was not declared in this scope
make: *_\* [all] Error 1

**Comment by chriserik** [comment]
I get the exact same compile error as @grantsmith1969 above.

$ gcc-v

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Debian 4.6.3-14+rpi1' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix

**Comment by mannkind** [comment]
Any luck with this?

**Comment by matheusbrat** [comment]
Sorry about this guys. I'm on a run this year, just graduated from computer science, and started an electronics intensive while working. So I'm really out of time. 

Soon I will get some vacations and will do my best to solve this.

Sorry again.
